name: Codacy
on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop
jobs:
  codacy-analysis-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          #tool: <CLIENT_SIDE_TOOL_NAME>
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true
          max-allowed-issues: 2147483647
