name: Test Github Actions
on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: "Setup"
        run: |
          sudo apt install -y libpcsclite-dev
          pip3 install conan
      - uses: actions/checkout@v2
      - name: "Build"
        run: |
          mkdir build
          cd build
          conan install .. -o LLA_BUILD_UNITTEST=True
          conan build ..
      - name: "Test"
        run: |
          ctest
  coverity:
    runs-on: ubuntu-latest
    - name: "Setup"
      run: |
        sudo apt install -y libpcsclite-dev
        pip3 install conan
    - uses: actions/checkout@v2
    - run: |
        mkdir build
        cd build
        conan install .. -o LLA_BUILD_UNITTEST=True
    - uses: vapier/coverity-scan-action@v1
    with:
      email: ${{ secrets.COVERITY_SCAN_EMAIL }}
      token: ${{ secrets.COVERITY_SCAN_TOKEN }}
      command: conan build ..

