name: Test Github Actions
on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc]
    steps:
      - name: "Setup"
        run: |
          sudo apt install -y libpcsclite-dev
          pip3 install conan
      - uses: actions/checkout@v2
      - name: "Build"
        env:
          CC: ${{ matrix.compiler }}
          CXX: ${{ matrix.compiler }}
        run: |
          mkdir build
          cd build
          conan install .. -o LLA_BUILD_UNITTEST=True
          conan build ..
      - name: "Test"
        run: |
          cd build
          ctest
  codacy-analysis-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          #tool: <CLIENT_SIDE_TOOL_NAME>
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true
          max-allowed-issues: 2147483647
