name: Test Github Actions
on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v2
      - run: |
          sudo apt install -y libpcsclite-dev
          pip3 install conan
  build:
    needs: setup
    runs-on: ubuntu-latest
    streps:
      - run: |
          mkdir build
          cd build
          conan install .. -o LLA_BUILD_UNITTEST=True
          conan build ..
  test:
    needs: build
    runs-on: ubuntu-latest
    streps:
      - run: |
          ctest
